name: Rust saves cache
description: Saves Rust build artifacts
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}
    - uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}
