name: Rust Cargo cache
description: Saves and restores Rust build cache in target and ~/.cargo directories
branding:
  icon: coffee
  color: orange
inputs: {}
outputs: {}
runs:
  using: composite
  env:
    directory: ${{ runner.temp }}/cargo_cache
  steps:
    - shell: bash
      run: |
        mkdir -p $directory

        for file in $(find . -name Cargo.lock | sort); do
          target_file=$directory/$file
          mkdir -p $(dirname $target_file)
          cp $file $target_file
        done

        cargo install --list > $directory/install.txt
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/.*
          ~/.cargo/bin
          ~/.cargo/git
          ~/.cargo/index
          ~/.cargo/registry
          **/target/
        key: cargo-cache-v1-${{ runner.os }}-${{ github.job }}-${{ github.action }}-${{ hashFiles(join(env.directory, '/**')) }}
