name: Rust saves cache
description: Saves Rust build artifacts
inputs: {}
outputs: {}
runs:
  using: composite
  env:
    DIRECTORY: /tmp/cargo-cache
  steps:
    - run: $
    - run: |
        file=/tmp/cargo-cache/cargo_config.toml

        cargo install --list > $file
        echo cargo_install_list_file=$file >> ${{ github.env }}
    - run: |
        file=/tmp/cargo_install_list.txt

        cargo install --list > $file
        echo cargo_install_list_file=$file >> ${{ github.env }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}
    - uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}
