name: Rust saves cache
description: Saves Rust build artifacts
branding:
  icon: coffee
  color: orange
inputs:
  path:
    description: Cargo manifest directory
    required: false
    default: .
outputs: {}
runs:
  using: composite
  steps:
    - shell: bash
      run: echo CARGO_CACHE_DIRECTORY=.cargo_cache >> ${{ github.env }}
    - shell: bash
      run: mkdir -p $CARGO_CACHE_DIRECTORY
    - shell: bash
      run: |
        file=~/.cargo/config.toml

        touch $file
        cp $file $CARGO_CACHE_DIRECTORY
    # TODO Move this to post steps.
    # https://github.com/actions/runner/issues/1478
    - shell: bash
      run: cargo install --list > $CARGO_CACHE_DIRECTORY/install.txt
    - shell: bash
      run: cp ${{ inputs.path }}/Cargo.lock $CARGO_CACHE_DIRECTORY
    - shell: bash
      run: >
        echo CARGO_CACHE_KEY=${{ runner.os }}-${{ hashFiles(join(env.CARGO_CACHE_DIRECTORY, '/*')) }}
        >> ${{github.env}}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: cargo-cache-${{ github.job }}-${{ github.action }}-${{ env.CARGO_CACHE_KEY }}
    - uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}/target/*/deps
        key: cargo-cache-${{ github.job }}-${{ github.action }}-${{ env.CARGO_CACHE_KEY }}
