name: Rust saves cache
description: Saves Rust build artifacts
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - run: echo cargo_config=$(cat ~/.cargo/config.toml) >> ${{ github.env }}
    - run: echo cargo_install_list=$(cargo install --list) >> ${{ github.env }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}
    - uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}
