name: Rust saves cache
description: Saves Rust build artifacts
inputs: {}
outputs: {}
runs:
  using: composite
  env:
    DIRECTORY: /tmp/cargo-cache
  steps:
    - run: mkdir -p $DIRECTORY
    - run: |
        file=$DIRECTORY/config.toml

        cargo install --list > $file
        echo cargo_install_list_file=$file >> ${{ github.env }}
    - run: |
        file=$DIRECTORY/install.txt

        cargo install --list > $file
        echo cargo_install_list_file=$file >> ${{ github.env }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}
    - uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}
