name: Rust Cargo cache
description: Saves and restores Rust build cache in target and ~/.cargo directories
branding:
  icon: coffee
  color: orange
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - id: setup
      shell: bash
      run: echo directory=.cargo_cache >> ${{ github.output }}
    - shell: bash
      run: |
        directory=${{ steps.setup.outputs.directory }}
        mkdir -p $directory

        for file in $(find . -name Cargo.lock); do
          target_file=$directory/$file
          mkdir -p $(dirname $target_file)
          cp $file $target_file
        done

        cargo install --list > $directory/install.txt
    - uses: actions/cache@v4
      with:
        # target/
        path: |
          ~/.cargo/.*
          ~/.cargo/bin
          ~/.cargo/git
          ~/.cargo/index
          ~/.cargo/registry
          **/target/
        key: cargo-cache-v2-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ hashFiles(format('{0}/**', steps.setup.outputs.directory)) }}
        restore-keys: |
          cargo-cache-v2-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ hashFiles(format('{0}/**', steps.setup.outputs.directory)) }}
          cargo-cache-v2-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-
          cargo-cache-v2-${{ runner.os }}-${{ github.workflow }}-
          cargo-cache-v2-${{ runner.os }}-
    - run: rm -rf .cargo_cache
      shell: bash
