name: Rust saves cache
description: Saves Rust build artifacts
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - shell: bash
      run: echo CARGO_CACHE_DIRECTORY=/tmp/cargo_cache >> ${{ github.env }}
    - shell: bash
      run: mkdir -p $CARGO_CACHE_DIRECTORY
    - shell: bash
      run: |
        file=~/.cargo/config.toml

        touch $file
        cp $file $CARGO_CACHE_DIRECTORY
    - shell: bash
      run: cargo install --list > $CARGO_CACHE_DIRECTORY/install.txt
    - shell: bash
      run: >
        echo CARGO_CACHE_KEY=${{ runner.os }}-${{ hashFiles(format('{0}/{1}', env.CARGO_CACHE_DIRECTORY, '*')) }}
        >> ${{github.env}}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ env.CARGO_CACHE_KEY }}
    - uses: actions/cache@v3
      with:
        path: target/*/deps
        key: ${{ env.CARGO_CACHE_KEY }}
