name: Rust saves cache
description: Saves Rust build artifacts
inputs: {}
outputs: {}
runs:
  using: composite
  env:
    DIRECTORY: /tmp/cargo_cache
  steps:
    - run: mkdir -p $DIRECTORY
    - run: |
        config_file=~/.cargo/config.toml
        file=$DIRECTORY/config.toml

        if [ -r $config_file ]; then
          cp $config_file $file
        fi
    - run: |
        file=$DIRECTORY/install.txt

        cargo install --list > $file
        echo cargo_install_list_file=$file >> ${{ github.env }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ hashFiles([env.DIRECTORY, "*"], "/") }}
    - uses: actions/cache@v3
      with:
        path: target/*/deps
        key: ${{ runner.os }}-${{ hashFiles([env.DIRECTORY, "*"], "/") }}
