name: Rust Cargo cache
description: Saves and restores Rust build cache in target and ~/.cargo directories
branding:
  icon: coffee
  color: orange
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - shell: bash
      run: echo directory=.cargo_cache >> ${{ github.env }}
    - shell: bash
      run: echo paths=$(find . -name Cargo.lock | sed s/Cargo.lock/target/) >> ${{ github.env }}
    - shell: bash
      run: mkdir -p $directory
    - shell: bash
      run: |
        file=~/.cargo/config.toml

        touch $file
        cp $file $directory
    - shell: bash
      run: cp $(find . -name Cargo.lock) $directory
    # TODO Move this to post steps and remove timestamps from keys.
    # https://github.com/actions/runner/issues/1478
    - shell: bash
      run: cargo install --list > $directory/install.txt
    - shell: bash
      run: echo timestamp=$(date +%s) >> ${{ github.env }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo ${{ env.paths }}
        key: cargo-cache-${{ runner.os }}-${{ github.job }}-${{ github.action }}-${{ hashFiles(join(env.directory, '/*')) }}-${{ env.timestamp }}
        restore-keys: |
          cargo-cache-${{ runner.os }}-
          cargo-cache-${{ runner.os }}-${{ github.job }}-
          cargo-cache-${{ runner.os }}-${{ github.job }}-${{ github.action }}-
          cargo-cache-${{ runner.os }}-${{ github.job }}-${{ github.action }}-${{ hashFiles(join(env.directory, '/*')) }}-
