name: Rust saves cache
description: Saves Rust build artifacts
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}
    - uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-primes
    - uses: ruby/setup-ruby@v1
    - uses: homebrew/actions/setup-homebrew@master
    - run: tools/ci/setup.sh
      shell: bash
